# Generated by Django 4.1.2 on 2022-10-31 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuspenyu', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Konservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('jenis_penyu', models.CharField(max_length=100)),
                ('status_keberadaan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_utspbo1.status')),
            ],
        ),
    ]
