# Generated by Django 4.1.2 on 2022-10-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konservasi',
            old_name='status_keberadaan',
            new_name='Status_keberadaan',
        ),
        migrations.AlterField(
            model_name='status',
            name='statuspenyu',
            field=models.CharField(max_length=100),
        ),
    ]
