# Generated by Django 4.1.2 on 2022-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo1', '0002_rename_status_keberadaan_konservasi_status_keberadaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konservasi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
