# Generated by Django 4.1.2 on 2022-11-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo1', '0003_konservasi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konservasi',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
