# Generated by Django 4.1.2 on 2022-11-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo1', '0004_alter_konservasi_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konservasi',
            name='image',
        ),
        migrations.AddField(
            model_name='konservasi',
            name='img',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
