# Generated by Django 4.1.2 on 2023-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo1', '0005_remove_konservasi_image_konservasi_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=100)),
            ],
        ),
    ]
