# Generated by Django 4.1.2 on 2023-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo1', '0006_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasi',
            name='koordinat',
            field=models.IntegerField(null=True),
        ),
    ]
